### ISSUE TITLE
Full usage?

### ISSUE THREAD

**Issue by Kagetsuki** [masiuchi/mt-data_api-client#10]
Would it be possible to outline a few use cases in the README? Specifically, I'm unsure on how I'm supposed to authenticate with this client. From the specs it appears as if you're doing it by hand somehow. Also, I'm unsure of how you would use this to do something like upload a file ~ https://www.movabletype.jp/developers/data-api/v3-reference.html#assets-upload-post ? Read the file contents into the :file option in the call?

**Comment by masiuchi** [comment]
@Kagetsuki 
Thank you for your comment.

> I'm unsure on how I'm supposed to authenticate with this client.

Please see the following sample to authenticate.
Sorry there is a bug. I will update README.md after fixing it.

```ruby
client = MT::DataAPI::Client.new(
  base_url: 'http://localhost/mt/mt-data-api.cgi',
  client_id: 'mt-ruby'
)

# call authenticate endpoint and 
client.call(:authenticate, {
  username: 'username'
  password: 'webservice password',
  clientId: 'mt-ruby',  # required. this is a bug.
})

# call the endpoint that requires authenticate
result_json = client.call(:list_plugins)
```

> Read the file contents into the :file option in the call?

Sorry, currently it cannot upload file. I will fix it.

**Comment by Kagetsuki** [comment]
Thanks!

I actually ended up implementing some bare bones code to do uploads. Give me a heads up if you want to see it and I'll throw it in a gist.

Closing issue as I've got the info I wanted.
